$ ./signinup 
2018/11/16 13:14:18 databse ping success
2018/11/16 13:14:22 /signin
2018/11/16 13:14:22 sign in failed, we dont have a record for the account
2018/11/16 13:14:33 /signup
2018/11/16 13:14:33 successfully signed up j1 $2a$08$XqiqiYY/c8C80152A5bbm.hKwVdKWV0qsXoIy.xhvD8ov6vs1BOeS
2018/11/16 13:14:38 /signin
2018/11/16 13:14:38 matched and signed in
2018/11/16 13:14:45 /signin
2018/11/16 13:14:45 sign in failed, we dont have a record for the account

$ curl --header "Content-Type:application/json" --request POST --data '{"username":"j1", "password":"c1"}' http://localhost:8000/signin
$ curl --header "Content-Type:application/json" --request POST --data '{"username":"j1", "password":"c1"}' http://localhost:8000/signup
$ curl --header "Content-Type:application/json" --request POST --data '{"username":"j1", "password":"c1"}' http://localhost:8000/signin
$ curl --header "Content-Type:application/json" --request POST --data '{"username":"j2", "password":"c2"}' http://localhost:8000/signin

mydb=# select * from users;
 username |                           password                           
----------+--------------------------------------------------------------
 j1       | $2a$08$XqiqiYY/c8C80152A5bbm.hKwVdKWV0qsXoIy.xhvD8ov6vs1BOeS
(1 row)
